version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: orbitr-postgres
    environment:
      POSTGRES_DB: orbitr
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d orbitr"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
